### ISSUE TITLE
Tinfoil also detects _bootloader folder now

### ISSUE THREAD

**Issue by hstraten** [wilsam239/Tinfoil-Workaround#1]
Tinfoil also detects _bootloader folder now. (R81)
renaming it to something else (like just an underscore or something else) it is fine again.
Maybe give an option to customize the target folder name / filenames?

**Comment by ElecTriX666** [comment]
I agree. A random string chosen by user would be the smartest.

I tried to rename bootloader to bootloaderp but for some reason it still finds it. I assume that Tinfoil uses a wildcard like `*bootloader*`

**Comment by wilsam239** [comment]
Thanks for the feedback, I'll update it when I get a chance, will be an easy change to change it to another string, but changing to user entered string will be a bit trickier.

Will be unable to get to it for 3 weeks or so while I'm on holiday, feel free to make a PR for it!

**Comment by elghinnarisa** [comment]
The only file it looks for is patches.ini. Renaming said file to something else and it works without issue. Perhaps rename file instead of the folder?

**Comment by wilsam239** [comment]
Thanks for the tip! I'll look at a fix when I return

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by elidoe89** [comment]
I tried to change the folder name to my own name and Tinfoil worked fine.
I'm a total noob, is it possible to make it random or define a specific text? that will make it easier for now.
Btw how to compile files on windows?

**Comment by lialosiu** [comment]
for new version of Tinfoil, `__bootloader` do not work. ( double `_` )

I try to rename to `ootloader` (remove letter `b`), it worked. 

so maybe Tinfoil check the string `bootloader` now?

**Comment by wilsam239** [comment]
Fixed in the latest release, please let me know how it goes.
